### ISSUE TITLE
tron on OS X without Poll Reactor

### ISSUE THREAD

**Issue by AlexIzydorczyk** [Yelp/Tron#305]
Hi,

I'm getting an error 

```
Traceback (most recent call last):
  File "/usr/local/bin/trond", line 11, in <module>
    from tron import trondaemon
  File "/Library/Python/2.7/site-packages/tron/trondaemon.py", line 10, in <module>
    from twisted.internet import pollreactor, defer
  File "/Library/Python/2.7/site-packages/twisted/internet/pollreactor.py", line 18, in <module>
    from select import error as SelectError, poll
ImportError: cannot import name poll
```

From my understanding, poll is not supported on OS X (rather than using pollreactor I could be using cfreactor). Am I correct/is this the case?

If so, I imagine I can easily modify trondaemon.py to use cfreactor? 

Thanks,
Alex

**Comment by yyejun** [comment]
I think that's correct.

**Comment by yms9654** [comment]
+1
