### ISSUE TITLE
Problem start trond

### ISSUE THREAD

**Issue by giammy2290** [Yelp/Tron#307]
Hi, i have create the user tron and i have installed tron with pip, when i start the service i receive this log:

/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/tron/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
tron@trond:~/.ssh$ 2015-06-11 15:39:57,589 tron.trondaemon ERROR Error in configuration /var/lib/tron/config/: 'KnownHosts' object has no attribute '_entries'
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/tron/trondaemon.py", line 194, in _run_mcp
    self.mcp.initial_setup()
  File "build/bdist.linux-x86_64/egg/tron/mcp.py", line 67, in initial_setup
    self._load_config()
  File "build/bdist.linux-x86_64/egg/tron/mcp.py", line 61, in _load_config
    self.apply_config(self.config.load(), reconfigure=reconfigure)
  File "build/bdist.linux-x86_64/egg/tron/mcp.py", line 84, in apply_config
    apply_master_configuration(master_config_directives, master_config)
  File "build/bdist.linux-x86_64/egg/tron/mcp.py", line 23, in apply_master_configuration
    func(_args)
  File "build/bdist.linux-x86_64/egg/tron/node.py", line 82, in update_from_config
    instance._update_nodes(node_configs, ssh_options, known_hosts, ssh_config)
  File "build/bdist.linux-x86_64/egg/tron/node.py", line 87, in _update_nodes
  2015-06-11 15:39:57,589 tron.trondaemon ERROR Error in configuration /var/lib/tron/config/: 'KnownHosts' object has no attribute '_entries'
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/tron/trondaemon.py", line 194, in _run_mcp
    self.mcp.initial_setup()
  File "build/bdist.linux-x86_64/egg/tron/mcp.py", line 67, in initial_setup
    self._load_config()
  File "build/bdist.linux-x86_64/egg/tron/mcp.py", line 61, in _load_config
    self.apply_config(self.config.load(), reconfigure=reconfigure)
  File "build/bdist.linux-x86_64/egg/tron/mcp.py", line 84, in apply_config
    apply_master_configuration(master_config_directives, master_config)
  File "build/bdist.linux-x86_64/egg/tron/mcp.py", line 23, in apply_master_configuration
    func(_args)
  File "build/bdist.linux-x86_64/egg/tron/node.py", line 82, in update_from_config
    instance._update_nodes(node_configs, ssh_options, known_hosts, ssh_config)
  File "build/bdist.linux-x86_64/egg/tron/node.py", line 87, in _update_nodes
    pub_key = known_hosts.get_public_key(config.hostname)
  File "build/bdist.linux-x86_64/egg/tron/node.py", line 177, in get_public_key
    for entry in self._entries:
AttributeError: 'KnownHosts' object has no attribute '_entries'
  pub_key = known_hosts.get_public_key(config.hostname)
  File "build/bdist.linux-x86_64/egg/tron/node.py", line 177, in get_public_key
    for entry in self._entries:
AttributeError: 'KnownHosts' object has no attribute '_entries'

this is my config

   # identities:
   #      - /root/.ssh/id_rsa
ssh_options:
  identities:
       - /home/tron/.ssh/id_rsa
  agent: false

notification_options:
  smtp_host: localhost
  notification_addr: <email>

nodes:
- name: local
  hostname: 'localhost'
  username: 'tron'
  jobs:
  #  - name: "getting_node_info"
  #    node: local
  #    schedule: "interval 10 mins"
  #    actions:
  #      - name: "uname"
  #        command: "uname -a"
  #      -
  #        name: "cpu_info"
  #        command: "cat /proc/cpuinfo"
  #        requires: [uname]

**Comment by solarkennedy** [comment]
@giammy2290 please re-open if you still need help.
